public enum SoundType
{
    BackgroundMainMenu,
    BackgroundGamePlay,
    PlayerAttack,
    PlayerShoot,
    PlayerWarp,
    PlayerBurn,
    PlayerHeal,
    LevelUp,
    EnemyAttack,
    EnemyDeath,
    Explosion,
    EnemySpawn,
    EnemyShoot,
    ItemPickup,
    GameOver,
    ButtonClick,
    UseItem
}